version: 0.2

phases:
  build:
    commands:
      - echo $ACCOUNTNAME
      - docker build -t spinnakerdemo:latest .

  post_build:
    commands:
      - echo logging in to AWS ECR...
      - eval aws ecr get-login --no-include-email --region us-east-1

      - docker tag spinnakerdemo:latest $ACCOUNTNAME.dkr.ecr.us-east-1.amazonaws.com/cicdforspinnaker:latest
      - docker push $ACCOUNTNAME.dkr.ecr.us-east-1.amazonaws.com/cicdforspinnaker:latest
