version: 0.2

phases:
  build:
    commands:
      - echo $ACCOUNTNAME
      - docker build -t cicdforspinnaker .

  post_build:
    commands:
      - echo logging in to AWS ECR...

      - docker tag cicdforspinnaker:latest $ACCOUNTNAME.dkr.ecr.us-east-1.amazonaws.com/cicdforspinnaker:latest
      - $(aws ecr get-login --no-include-email --region us-east-1)
      - docker push $ACCOUNTNAME.dkr.ecr.us-east-1.amazonaws.com/cicdforspinnaker:latest
