version: 0.2

phases:
  build:
    commands:
      - echo $ACCOUNTNAME
      - docker build -t spinnakerdemo .

  post_build:
    commands:
      - echo logging in to AWS ECR...
      - eval aws ecr get-login --no-include-email --region us-east-1

      - ddocker tag spinnakerdemo:latest 031342435657.dkr.ecr.us-east-1.amazonaws.com/spinnakerdemo:latest
      - docker push 031342435657.dkr.ecr.us-east-1.amazonaws.com/cicdforspinnaker:latest
